[package]
name = "mega_engineering_core"
version = "0.1.0"
edition = "2024"
authors = ["Yağız Yağlı"],
description = "High-performance computational engine for Mega Engineering Library"

[lib]
name = "core_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
ndarray = "0.15"
