"""
Mega Engineering Library - Agricultural & Biosystems Engineering: Agricultural Machinery Module
Handles vehicle drawbar power mechanics, implement draft resistances, and field capacities.
Validated against standard machinery metrics (e.g., ASABE standards).
"""

from englib.common.exceptions import GeometricViolationError, PhysicalBoundaryError

class AgriculturalMachinery:

    @staticmethod
    def calculate_drawbar_power(draft_force_kn: float, travel_speed_m_s: float) -> float:
        """
        Calculates the active drawbar power (P) generated by an agricultural tractor pull.
        Power = Draft Force (kN) * Travel Speed (m/s)
        Unit: Kilowatts (kW)
        """
        if draft_force_kn < 0:
            raise PhysicalBoundaryError("Draft pull pulling force vector magnitude cannot be negative.")
        if travel_speed_m_s <= 0:
            raise GeometricViolationError("Agricultural tractor actual forward speed must be positive and non-zero.")

        return draft_force_kn * travel_speed_m_s
